minishlink_web_push:
  VAPID:
    subject: '%env(VAPID_SUBJECT)%'        # can be an URL or a mailto:
    publicKey: '%env(VAPID_PUBLIC_KEY)%'   # uncompressed public key P-256 encoded in Base64-URL
    privateKey: '%env(VAPID_PRIVATE_KEY)%' # the secret multiplier of the private key encoded in Base64-URL
  ttl: 60                                  # Time to Live of notifications in seconds
  # urgency: ~                             # can be very-low / low / normal / high
  # topic: ~                               # default identifier for your notifications
  timeout: 5                               # Timeout of each request in seconds
  automatic_padding: true                  # pad messages automatically for better security (against more bandwith usage)
